spring.application.name=roserank

spring.datasource.url=jdbc:postgresql://localhost:5432/roserank
spring.datasource.username=jackr
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update

clerk.secret.key=${KEY}
clerk.webhook.secret=${SECRET}